language: node_js
node_js:
  - "11.0"
branches:
  only:
    - angular-universal
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build:prerender
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: FIREBASE_TOKEN
  on:
    all_branches: true
